# Generated by Django 5.0.3 on 2024-03-22 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("born_date", models.DateTimeField(default=datetime.datetime.now)),
                ("born_location", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
