# Generated by Django 5.0.3 on 2024-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_alter_author_born_location_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.TextField(),
        ),
    ]
